spring:
  #V-27,paso 31, hacemos las siguientes configuraciones
  application:
    name: registry-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
