spring:
  application:
    #V-67,Paso 7.0 ,le agregamos el fallback
    name: companies-crud-fallback
server:
  servlet:
    #le ponemos la misma nomenclatura.
    context-path: /companies-crud-fallback
  port: 8787
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
