spring:
  #Vid 101
  profiles:
    default: default
  application:
    name: auth-server
  #Vid 103
  h2:
    console:
     enabled: true
  config:
    import: optional:configserver:http://localhost:7777
  datasource:
    url: jdbc:h2:mem:users;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#Vid 101
server:
  #El pone 3000,pero dejarlo así,solo así funciona.
  port: 3030
  servlet:
    context-path: /auth-server
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
