spring:
  #V-46,paso 40 ponemos las configuraciones
  application:
    name: report-ms
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
  #Vid 80
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        bindings:
          consumerReport-out-0:
            destination: consumerReport
server:
  servlet:
    context-path: /report-ms
  #Le pone puerto 0, en el V-64
  port: 7070
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
