spring:
  datasource:
    #Paso 38,hace las configuraciones , del datasource,estas variables vienen de Git
    username: ${db.username}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
    url: ${db.url}
    #De esta forma ponemos las variables de entorno
    #password:udemy
    password: ${db.password}
  #V-28,paso 32
  application:
    name: companies-crud
  #V-36, al final el qa ,lo elimina
  profiles:
    #V-36,Paso 37 ponemos el default con el que trabajaremos,
    #Aqui podriamos trabajar con qa
    #default: qa
    default: default
  config:
    #el optional para que me regrese el objeto en un optional
    import: "optional:configserver:http://localhost:7777"
    #import: "optional:configserver:${CONFIG_SERVER_HOST}"
    #V-19,Paso 28, cuando se trabaja con microservicios es necesario poner el server
server:
  servlet:
    context-path: /companies-crud
    #En V-51 , le pone 0 que es un puerto aleatorio
    #En V-64, le vuelve a poner 0
  port: 8081
logging:
  #V-90,genera automaticamente las librerias
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
#Paso 33, ponemos eureka
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: ${EUREKA_URL}

#V-90,paso 3.5
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  #V-90
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  metrics:
    distribution:
      percentiles:
        do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        do.sleep.method.timed: true
        http.server.requests: true
      minimum-expected-value:
        do.sleep.method.timed: 100ms
        http.server.requests: 100ms
      maximum-expected-value:
        do.sleep.method.timed: 10s
        http.server.requests: 10s
      slo:
        do.sleep.method.timed: 300ms,500ms,1s,2s
        http.server.requests: 300ms,500ms,1s,2s
  endpoints:
    web:
      exposure:
        include: '*'