spring:
  datasource:
    #Vid 36 ,hace las configuraciones
    username: ${db.username}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
    url: ${db.url}
    password: ${db.password}
  application:
    name: companies-crud
  #Vid 36, al final el qa ,lo elimina
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
server:
  servlet:
    context-path: /companies-crud
  #En Vid 51 , le pone 0
  port: 8081
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/