#Vid 60
spring:
  application:
    name: gateway
  profiles:
    #Vid 114 cambia de eureka-on-cba oauth
    default: oauth2
server:
  port: 4040
eureka:
  client:
    #Se lo cambia a true en vid 64
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
