#V-60,Paso 1.0
spring:
  application:
    name: gateway
  profiles:
    #V-114 cambia de eureka-on-cba oauth
     #V-114,paso 3.53
    default: oauth2
    #default: eureka-on-cb
server:
  port: 4040
eureka:
  client:
    #Se lo cambia a true en v-64
    fetch-registry: true
    service-url:
      #Debe saber donde esta erueka
      defaultZone: http://localhost:8761/eureka/
